version: '3.5'
services:
  readme.blog.postgres:
    image: postgres:14-alpine
    container_name: readme.blog.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: readme-blog
    ports:
      - 5432:5432
    volumes:
      - readme.postgres.blog:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.blog

  readme.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - readme.blog

volumes:
  readme.postgres.blog:

networks:
  readme.blog:
    driver: bridge
